# Generated by Django 4.1.12 on 2023-10-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scénario',
            new_name='Scenario',
        ),
    ]
