# Generated by Django 4.1.12 on 2023-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_rename_scénario_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(help_text='Clé SSH')),
                ('username', models.CharField(help_text="Nom d'utilisateur SSH", max_length=255)),
                ('ip', models.GenericIPAddressField(help_text='Adresse IP de la machine distante')),
                ('port', models.PositiveIntegerField(default=22, help_text='Port SSH (par défaut à 22)')),
            ],
        ),
    ]
