# Generated by Django 4.1.12 on 2023-10-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_sshkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='action',
            field=models.FilePathField(help_text='Chemin vers le script Python à exécuter', path='path_to_scripts_directory'),
        ),
    ]
