# Generated by Django 4.1.12 on 2023-10-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_scenario_logs_alter_scenario_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='action',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='logs',
        ),
    ]
